export const FIELD_LABELS = {
  email: "FIELD_EMAIL",
  username: "FIELD_USERNAME",
  password: "FIELD_PASSWORD",
  confirmPassword: "FIELD_CONFIRM_PASSWORD",

  companyName: "FIELD_COMPANY_NAME",
  firstName: "FIELD_FIRST_NAME",
  lastName: "FIELD_LAST_NAME",
  gender: "FIELD_GENDER",
  country: "FIELD_COUNTRY",
  descriptionOfCompany: "FIELD_DESCRIPTION_OF_COMPANY",
  phone: "FIELD_PHONE",
  alternatePhone: "FIELD_ALTERNATE_PHONE",
  mainAddressStreet: "FIELD_MAIN_ADDRESS_STREET",
  mainAddressNo: "FIELD_MAIN_ADDRESS_NO",
  mainAddressPostCode: "FIELD_MAIN_ADDRESS_POST_CODE",
  mainAddressCity: "FIELD_MAIN_ADDRESS_CITY",
  billingAddressStreet: "FIELD_BILLING_ADDRESS_STREET",
  billingAddressNo: "FIELD_BILLING_ADDRESS_NO",
  billingAddressPostCode: "FIELD_BILLING_ADDRESS_POST_CODE",
  billingAddressCity: "FIELD_BILLING_ADDRESS_CITY",
  VATId: "FIELD_VATID",
  CountryCode: "FIELD_COUNTRY_CODE",
  nickName: "FIELD_NICKNAME",
  cuisineName: "FIELD_CUISINENAME",
};
